version: "3.5"

services:
  taurus:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    network_mode: "host"

networks:
  casetracking-shared:
    name: casetracking-shared
